twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        site_title: '%app.site_title%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'